#############################################################################
# Makefile for building: Rknn-yolov7
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  Rknn-yolov7.pro
# Template: app
# Command: /home/hgm/qt5.12.0_build/bin/qmake -o Makefile Rknn-yolov7.pro -spec myaarch64 CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /usr/bin/aarch64-linux-gnu-gcc
CXX           = /usr/bin/aarch64-linux-gnu-g++
DEFINES       = 
CFLAGS        = -pipe -O2 -march=armv8-a -lts -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=armv8-a -lts -O2 -march=armv8-a -lts -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Irknpu2/librknn_api/include -I../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4 -I3rdparty/rga/include -I3rdparty/mpp/include -I3rdparty/zlmediakit/include -I../../qt5.12.0_build/mkspecs/myaarch64
QMAKE         = /home/hgm/qt5.12.0_build/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/hgm/qt5.12.0_build/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/hgm/qt5.12.0_build/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Rknn-yolov71.0.0
DISTDIR = /home/hgm/QTDemo/Rknn-yolov7/.tmp/Rknn-yolov71.0.0
LINK          = /usr/bin/aarch64-linux-gnu-g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lpthread rknpu2/librknn_api/aarch64/librknnrt.so /home/hgm/VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/lib/libopencv_core.so /home/hgm/VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/lib/libopencv_imgcodecs.so /home/hgm/VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/lib/libopencv_video.so /home/hgm/VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/lib/libopencv_imgproc.so /home/hgm/VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/lib/libopencv_calib3d.so /home/hgm/VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/lib/libopencv_highgui.so 3rdparty/rga/libs/Linux/gcc-aarch64/librga.so 3rdparty/mpp/Linux/aarch64/librockchip_mpp.so 3rdparty/mpp/Linux/aarch64/librockchip_mpp.so.0 3rdparty/mpp/Linux/aarch64/librockchip_mpp.so.1 3rdparty/zlmediakit/aarch64/libmk_api.so   
AR            = /usr/bin/aarch64-linux-gnu-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /usr/bin/aarch64-linux-gnu-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = drawing.cpp \
		main.cc \
		mpp_decoder.cpp \
		mpp_encoder.cpp \
		postprocess.cc \
		preprocess.cc 
OBJECTS       = drawing.o \
		main.o \
		mpp_decoder.o \
		mpp_encoder.o \
		postprocess.o \
		preprocess.o
DIST          = labels_list.txt \
		../../qt5.12.0_build/mkspecs/features/spec_pre.prf \
		../../qt5.12.0_build/mkspecs/common/unix.conf \
		../../qt5.12.0_build/mkspecs/common/linux.conf \
		../../qt5.12.0_build/mkspecs/common/sanitize.conf \
		../../qt5.12.0_build/mkspecs/common/gcc-base.conf \
		../../qt5.12.0_build/mkspecs/common/gcc-base-unix.conf \
		../../qt5.12.0_build/mkspecs/common/g++-base.conf \
		../../qt5.12.0_build/mkspecs/common/g++-unix.conf \
		../../qt5.12.0_build/mkspecs/qconfig.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_charts.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_core.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_core_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_dbus.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_gui.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_input_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_network.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_network_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qml.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quick.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_serialport.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_service_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_sql.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_testlib.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_websockets.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_widgets.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_xml.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_zlib_private.pri \
		../../qt5.12.0_build/mkspecs/features/qt_functions.prf \
		../../qt5.12.0_build/mkspecs/features/qt_config.prf \
		../../qt5.12.0_build/mkspecs/myaarch64/qmake.conf \
		../../qt5.12.0_build/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../qt5.12.0_build/mkspecs/features/exclusive_builds.prf \
		../../qt5.12.0_build/mkspecs/features/toolchain.prf \
		../../qt5.12.0_build/mkspecs/features/default_pre.prf \
		../../qt5.12.0_build/mkspecs/features/resolve_config.prf \
		../../qt5.12.0_build/mkspecs/features/default_post.prf \
		../../qt5.12.0_build/mkspecs/features/resources.prf \
		../../qt5.12.0_build/mkspecs/features/qtquickcompiler.prf \
		../../qt5.12.0_build/mkspecs/features/warn_on.prf \
		../../qt5.12.0_build/mkspecs/features/qmake_use.prf \
		../../qt5.12.0_build/mkspecs/features/file_copies.prf \
		../../qt5.12.0_build/mkspecs/features/testcase_targets.prf \
		../../qt5.12.0_build/mkspecs/features/exceptions.prf \
		../../qt5.12.0_build/mkspecs/features/yacc.prf \
		../../qt5.12.0_build/mkspecs/features/lex.prf \
		Rknn-yolov7.pro drawing.h \
		drm_func.h \
		mpp_decoder.h \
		mpp_encoder.h \
		postprocess.h \
		preprocess.h \
		rga_func.h drawing.cpp \
		main.cc \
		mpp_decoder.cpp \
		mpp_encoder.cpp \
		postprocess.cc \
		preprocess.cc
QMAKE_TARGET  = Rknn-yolov7
DESTDIR       = 
TARGET        = Rknn-yolov7


first: all
####### Build rules

Rknn-yolov7:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Rknn-yolov7.pro ../../qt5.12.0_build/mkspecs/myaarch64/qmake.conf ../../qt5.12.0_build/mkspecs/features/spec_pre.prf \
		../../qt5.12.0_build/mkspecs/common/unix.conf \
		../../qt5.12.0_build/mkspecs/common/linux.conf \
		../../qt5.12.0_build/mkspecs/common/sanitize.conf \
		../../qt5.12.0_build/mkspecs/common/gcc-base.conf \
		../../qt5.12.0_build/mkspecs/common/gcc-base-unix.conf \
		../../qt5.12.0_build/mkspecs/common/g++-base.conf \
		../../qt5.12.0_build/mkspecs/common/g++-unix.conf \
		../../qt5.12.0_build/mkspecs/qconfig.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_charts.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_core.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_core_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_dbus.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_gui.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_input_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_network.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_network_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qml.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quick.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_serialport.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_service_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_sql.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_testlib.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_websockets.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_widgets.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_xml.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt5.12.0_build/mkspecs/modules/qt_lib_zlib_private.pri \
		../../qt5.12.0_build/mkspecs/features/qt_functions.prf \
		../../qt5.12.0_build/mkspecs/features/qt_config.prf \
		../../qt5.12.0_build/mkspecs/myaarch64/qmake.conf \
		../../qt5.12.0_build/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../qt5.12.0_build/mkspecs/features/exclusive_builds.prf \
		../../qt5.12.0_build/mkspecs/features/toolchain.prf \
		../../qt5.12.0_build/mkspecs/features/default_pre.prf \
		../../qt5.12.0_build/mkspecs/features/resolve_config.prf \
		../../qt5.12.0_build/mkspecs/features/default_post.prf \
		../../qt5.12.0_build/mkspecs/features/resources.prf \
		../../qt5.12.0_build/mkspecs/features/qtquickcompiler.prf \
		../../qt5.12.0_build/mkspecs/features/warn_on.prf \
		../../qt5.12.0_build/mkspecs/features/qmake_use.prf \
		../../qt5.12.0_build/mkspecs/features/file_copies.prf \
		../../qt5.12.0_build/mkspecs/features/testcase_targets.prf \
		../../qt5.12.0_build/mkspecs/features/exceptions.prf \
		../../qt5.12.0_build/mkspecs/features/yacc.prf \
		../../qt5.12.0_build/mkspecs/features/lex.prf \
		Rknn-yolov7.pro
	$(QMAKE) -o Makefile Rknn-yolov7.pro -spec myaarch64 CONFIG+=qtquickcompiler
../../qt5.12.0_build/mkspecs/features/spec_pre.prf:
../../qt5.12.0_build/mkspecs/common/unix.conf:
../../qt5.12.0_build/mkspecs/common/linux.conf:
../../qt5.12.0_build/mkspecs/common/sanitize.conf:
../../qt5.12.0_build/mkspecs/common/gcc-base.conf:
../../qt5.12.0_build/mkspecs/common/gcc-base-unix.conf:
../../qt5.12.0_build/mkspecs/common/g++-base.conf:
../../qt5.12.0_build/mkspecs/common/g++-unix.conf:
../../qt5.12.0_build/mkspecs/qconfig.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_charts.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_charts_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_concurrent.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_concurrent_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_core.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_core_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_dbus.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_dbus_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_edid_support_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_fb_support_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_gui.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_gui_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_input_support_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_multimedia.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_multimedia_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_network.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_network_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_printsupport.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_printsupport_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_qml.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_qml_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_qmltest.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_qmltest_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_quick.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_quick_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_quickwidgets.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_serialbus.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_serialbus_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_serialport.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_serialport_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_service_support_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_sql.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_sql_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_testlib.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_testlib_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_theme_support_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_webchannel.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_webchannel_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_websockets.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_websockets_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_widgets.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_widgets_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_xml.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_xml_private.pri:
../../qt5.12.0_build/mkspecs/modules/qt_lib_zlib_private.pri:
../../qt5.12.0_build/mkspecs/features/qt_functions.prf:
../../qt5.12.0_build/mkspecs/features/qt_config.prf:
../../qt5.12.0_build/mkspecs/myaarch64/qmake.conf:
../../qt5.12.0_build/mkspecs/features/spec_post.prf:
.qmake.stash:
../../qt5.12.0_build/mkspecs/features/exclusive_builds.prf:
../../qt5.12.0_build/mkspecs/features/toolchain.prf:
../../qt5.12.0_build/mkspecs/features/default_pre.prf:
../../qt5.12.0_build/mkspecs/features/resolve_config.prf:
../../qt5.12.0_build/mkspecs/features/default_post.prf:
../../qt5.12.0_build/mkspecs/features/resources.prf:
../../qt5.12.0_build/mkspecs/features/qtquickcompiler.prf:
../../qt5.12.0_build/mkspecs/features/warn_on.prf:
../../qt5.12.0_build/mkspecs/features/qmake_use.prf:
../../qt5.12.0_build/mkspecs/features/file_copies.prf:
../../qt5.12.0_build/mkspecs/features/testcase_targets.prf:
../../qt5.12.0_build/mkspecs/features/exceptions.prf:
../../qt5.12.0_build/mkspecs/features/yacc.prf:
../../qt5.12.0_build/mkspecs/features/lex.prf:
Rknn-yolov7.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Rknn-yolov7.pro -spec myaarch64 CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile Rknn-yolov7

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_qmlcache_make_all:
compiler_qmlcache_clean:
compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

drawing.o: drawing.cpp drawing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawing.o drawing.cpp

main.o: main.cc 3rdparty/rga/include/RgaUtils.h \
		postprocess.h \
		rknpu2/librknn_api/include/rknn_api.h \
		preprocess.h \
		3rdparty/rga/include/im2d.h \
		3rdparty/rga/include/im2d_version.h \
		3rdparty/rga/include/im2d_type.h \
		3rdparty/rga/include/rga.h \
		3rdparty/rga/include/im2d_common.h \
		3rdparty/rga/include/im2d_buffer.h \
		3rdparty/rga/include/im2d_single.h \
		3rdparty/rga/include/im2d_task.h \
		3rdparty/rga/include/im2d_mpi.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/core.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cvdef.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/hal/interface.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cv_cpu_helper.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/hal/msa_macros.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/fast_math.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/version.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/base.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/opencv_modules.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cvstd.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/neon_utils.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/vsx_utils.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/check.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/traits.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/matx.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/saturate.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/types.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/mat.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/bufferpool.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/mat.inl.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/persistence.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/operations.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cvstd.inl.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/utility.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/utils/tls.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/optim.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/ovx.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/imgcodecs.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

mpp_decoder.o: mpp_decoder.cpp mpp_decoder.h \
		3rdparty/mpp/include/rockchip/rk_mpi.h \
		3rdparty/mpp/include/rockchip/rk_mpi_cmd.h \
		3rdparty/mpp/include/rockchip/rk_vdec_cmd.h \
		3rdparty/mpp/include/rockchip/rk_type.h \
		3rdparty/mpp/include/rockchip/mpp_err.h \
		3rdparty/mpp/include/rockchip/rk_vdec_cfg.h \
		3rdparty/mpp/include/rockchip/rk_venc_cmd.h \
		3rdparty/mpp/include/rockchip/mpp_frame.h \
		3rdparty/mpp/include/rockchip/mpp_buffer.h \
		3rdparty/mpp/include/rockchip/mpp_meta.h \
		3rdparty/mpp/include/rockchip/mpp_packet.h \
		3rdparty/mpp/include/rockchip/rk_venc_rc.h \
		3rdparty/mpp/include/rockchip/rk_venc_cfg.h \
		3rdparty/mpp/include/rockchip/rk_venc_ref.h \
		3rdparty/mpp/include/rockchip/mpp_task.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpp_decoder.o mpp_decoder.cpp

mpp_encoder.o: mpp_encoder.cpp mpp_encoder.h \
		3rdparty/mpp/include/rockchip/mpp_frame.h \
		3rdparty/mpp/include/rockchip/mpp_buffer.h \
		3rdparty/mpp/include/rockchip/rk_type.h \
		3rdparty/mpp/include/rockchip/mpp_err.h \
		3rdparty/mpp/include/rockchip/mpp_meta.h \
		3rdparty/mpp/include/rockchip/mpp_packet.h \
		3rdparty/mpp/include/rockchip/rk_mpi.h \
		3rdparty/mpp/include/rockchip/rk_mpi_cmd.h \
		3rdparty/mpp/include/rockchip/rk_vdec_cmd.h \
		3rdparty/mpp/include/rockchip/rk_vdec_cfg.h \
		3rdparty/mpp/include/rockchip/rk_venc_cmd.h \
		3rdparty/mpp/include/rockchip/rk_venc_rc.h \
		3rdparty/mpp/include/rockchip/rk_venc_cfg.h \
		3rdparty/mpp/include/rockchip/rk_venc_ref.h \
		3rdparty/mpp/include/rockchip/mpp_task.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpp_encoder.o mpp_encoder.cpp

postprocess.o: postprocess.cc postprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o postprocess.o postprocess.cc

preprocess.o: preprocess.cc preprocess.h \
		3rdparty/rga/include/im2d.h \
		3rdparty/rga/include/im2d_version.h \
		3rdparty/rga/include/im2d_type.h \
		3rdparty/rga/include/rga.h \
		3rdparty/rga/include/im2d_common.h \
		3rdparty/rga/include/im2d_buffer.h \
		3rdparty/rga/include/im2d_single.h \
		3rdparty/rga/include/im2d_task.h \
		3rdparty/rga/include/im2d_mpi.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/core.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cvdef.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/hal/interface.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cv_cpu_helper.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/hal/msa_macros.h \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/fast_math.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/version.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/base.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/opencv_modules.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cvstd.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/neon_utils.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/vsx_utils.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/check.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/traits.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/matx.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/saturate.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/types.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/mat.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/bufferpool.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/mat.inl.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/persistence.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/operations.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/cvstd.inl.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/utility.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/utils/tls.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/optim.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/core/ovx.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/imgcodecs.hpp \
		../../VscodeDemo/Multithread-rknn/3568/include/3rdparty/opencv_450/include/opencv4/opencv2/imgproc.hpp \
		postprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preprocess.o preprocess.cc

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

